DROP DATABASE IF EXISTS HotelManagment;

CREATE DATABASE HotelManagment;

USE HotelManagment;

CREATE TABLE IF NOT EXISTS RoomType(TypeID INT NOT NULL AUTO_INCREMENT,
Type VARCHAR(45) NOT NULL,
PRIMARY KEY(TypeID)
);

CREATE TABLE IF NOT EXISTS ROOM
(RoomID INT NOT NULL AUTO_INCREMENT,
FloorNum INT NOT NULL,
RoomNum INT NOT NULL,
Occupancy INT NOT NULL,
TypeID INT NOT NULL,
PRIMARY KEY (RoomID),
CONSTRAINT fk_RoomTypeID FOREIGN KEY(TypeID) REFERENCES RoomType(TypeID)
);

CREATE TABLE IF NOT EXISTS Rate
(RateID INT NOT NULL AUTO_INCREMENT,
TimeOfYear DATE NOT NULL,
TypeID INT NOT NULL,
Rate DECIMAL(5,2) NOT NULL,
PRIMARY KEY(RateID),
CONSTRAINT fk_RateTypeID FOREIGN KEY (TypeID) REFERENCES RoomType(TypeID)
);

CREATE TABLE IF NOT EXISTS Promotion
(PromotionID INT NOT NULL AUTO_INCREMENT,
Discount DECIMAL(5,2) NOT NULL,
BeginDate DATE NOT NULL,
EndDate DATE NOT NULL,
PRIMARY KEY(PromotionID)
);

CREATE TABLE IF NOT EXISTS RoomAddOn
(AddOnID INT NOT NULL AUTO_INCREMENT,
RoomID INT NOT NULL,
AddOnTypes VARCHAR(45) NOT NULL,
Quantity INT NOT NULL,
Fee DECIMAL(5,2) NOT NULL,
PRIMARY KEY(AddOnID),
CONSTRAINT fk_RoomID FOREIGN KEY (RoomID) REFERENCES Room (RoomID)
);

CREATE TABLE IF NOT EXISTS Customer
(CustomerID INT NOT NULL AUTO_INCREMENT,
FName VARCHAR(45) NOT NULL,
LName VARCHAR(45) NOT NULL,
Phone VARCHAR(10) NOT NULL,
Email VARCHAR(45) NOT NULL,
PRIMARY KEY (CustomerID)
);

CREATE TABLE IF NOT EXISTS Reservation
(ReservationID INT NOT NULL AUTO_INCREMENT,
BeginDate DATE NOT NULL,
EndDate DATE NOT NULL,
CustomerID INT NOT NULL,
PromotionID INT NOT NULL, 
PRIMARY KEY (ReservationID),
CONSTRAINT fk_CustomerID FOREIGN KEY (CustomerID) REFERENCES Customer(CustomerID),
CONSTRAINT fk_PromotionID FOREIGN KEY(PromotionID) REFERENCES Promotion(PromotionID)
);

CREATE TABLE IF NOT EXISTS Guest
(GuestID INT NOT NULL AUTO_INCREMENT,
ReservationID INT NOT NULL,
RoomID INT NOT NULL,
FName VARCHAR (45) NOT NULL,
LName VARCHAR (45) NOT NULL,
Age INT NOT NULL,
PRIMARY KEY(GuestID),
CONSTRAINT fk_GuestReservationID FOREIGN KEY (ReservationID) REFERENCES Reservation(ReservationID),
CONSTRAINT fk_GuestRoomID FOREIGN KEY (RoomID) REFERENCES Room(RoomID)
);

CREATE TABLE IF NOT EXISTS BillSummary
(BillID INT NOT NULL AUTO_INCREMENT,
ReservationID INT NOT NULL,
BillDate DATE NOT NULL,
Tax DECIMAL (4,2) ,
Total DECIMAL (5,2) NOT NULL,
PRIMARY KEY (BillID),
CONSTRAINT fk_BillReservationID FOREIGN KEY(ReservationID) REFERENCES Reservation (ReservationID)
);

CREATE TABLE IF NOT EXISTS BillDetails
(BillDetailsID INT NOT NULL AUTO_INCREMENT,
ReservationID INT NOT NULL,
RoomID INT NOT NULL,
AddOnID INT NOT NULL,
BillDetails VARCHAR(45) NOT NULL,
Charge DECIMAL (5,2) NOT NULL,
BillDate DATE NOT NULL,
PRIMARY KEY (BillDetailsID),
CONSTRAINT fk_BillDetailsReservationID FOREIGN KEY (ReservationID) REFERENCES Reservation(ReservationID),
CONSTRAINT fk_BillDetailsRoomID FOREIGN KEY (RoomID) REFERENCES Room (RoomID),
CONSTRAINT fk_BillDetailsAddOnID FOREIGN KEY (AddOnID) REFERENCES RoomAddON (AddOnID)
);